name       : ogre
version    : 1.9.0
release    : 2
source     :
    - https://bitbucket.org/sinbad/ogre/get/v1-9-0.tar.gz : ead2baa807903b740e726ebf2f205ad2de9f9aacaeeae0a38fc3e29184f50f5d
license    : MIT
component  : programming
summary    : OGRE (Object-Oriented Graphics Rendering Engine) is a scene-oriented,
    flexible 3D engine
description: |
    OGRE (Object-Oriented Graphics Rendering Engine) is a scene-oriented, flexible 3D engine
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(glew)
    - pkgconfig(freetype2)
    - pkgconfig(OIS)
    - pkgconfig(tinyxml)
    - pkgconfig(xaw7)
    - pkgconfig(xrandr)
    - pkgconfig(xt)
    - intel-tbb-devel
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/fix_mesh.patch
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DOGRE_BUILD_SAMPLES=0 \
    .
build      : |
    %make
install    : |
    %make_install
patterns   :
    - devel :
        - /usr/lib/OGRE/*.so
        - /usr/lib/OGRE/cmake
