name       : ogre
version    : 1.10.5
release    : 17
source     :
    - https://github.com/OGRECave/ogre/archive/v1.10.5.tar.gz : 452bc615e8c454fb79c65dd9092ad2a53e988e847b35a76b38fd4212e76c05e5
license    : MIT
component  : programming.library
summary    : OGRE (Object-Oriented Graphics Rendering Engine) is a scene-oriented,
    flexible 3D engine
description: |
    OGRE (Object-Oriented Graphics Rendering Engine) is a scene-oriented, flexible 3D engine written in C++ designed to make it easier and more intuitive for developers to produce applications utilizing hardware-accelerated 3D graphics.
patterns   :
    - devel :
        - /usr/lib/OGRE/*.so
        - /usr/lib/OGRE/cmake
builddeps  :
    - pkgconfig(OIS)
    - pkgconfig(OpenEXR)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(python3)
    - pkgconfig(sdl2)
    - pkgconfig(tinyxml)
    - pkgconfig(xaw7)
    - pkgconfig(xrandr)
    - pkgconfig(xt)
    - pkgconfig(zziplib)
    - intel-tbb-devel
    - libboost-devel
    - swig
setup      : |
    %cmake . -DCMAKE_BUILD_TYPE=Release \
             -DOGRE_BUILD_SAMPLES=FALSE \
             -DOGRE_BUILD_TESTS=FALSE \
             -DOGRE_LIB_DIRECTORY=%libdir%
build      : |
    %make
install    : |
    %make_install
