name       : ogre
version    : 1.10.5
release    : 3
source     :
    - https://bitbucket.org/sinbad/ogre/get/v1-10-5.tar.gz : f05b77ea37fba9dd5eb7b14adf294412a97dd3faa4099189ebf8742e3c6ff7ae
license    : MIT
component  : programming
summary    : OGRE (Object-Oriented Graphics Rendering Engine) is a scene-oriented, flexible 3D engine
description: |
    OGRE (Object-Oriented Graphics Rendering Engine) is a scene-oriented,
    flexible 3D engine written in C++ designed to make it easier and more
    intuitive for developers to produce applications utilizing
    hardware-accelerated 3D graphics. The class library abstracts all the
    details of using the underlying system libraries like Direct3D and
    OpenGL and provides an interface based on world objects and other
    intuitive classes.
patterns   :
    - devel :
        - /usr/lib/OGRE/*.so
        - /usr/lib/OGRE/cmake
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(freetype2)
    - pkgconfig(OIS)
    - pkgconfig(OpenEXR)
    - pkgconfig(python-3.5)
    - pkgconfig(sdl2)
    - pkgconfig(tinyxml)
    - pkgconfig(xaw7)
    - pkgconfig(xrandr)
    - pkgconfig(xt)
    - pkgconfig(zziplib)
    - intel-tbb-devel
    - libboost-devel
    - swig
setup      : |
    %cmake . -DCMAKE_BUILD_TYPE=Release \
             -DOGRE_BUILD_SAMPLES=FALSE \
             -DOGRE_BUILD_TESTS=FALSE \
             -DOGRE_LIB_DIRECTORY=%libdir%
build      : |
    %make
install    : |
    %make_install

